version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: wishoria-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notionApp
      POSTGRES_USER: ${DATABASE_LOGIN}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: