app:
  url:
    frontend: ${FRONTEND_URL:localhost:3000}
    backend: ${BACKEND_URL:localhost:8080}
  limits:
    max-wishlists: 50
    max-items-per-list: 50
    max-shares-per-wishlist: 30

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  refresh:
    expiration:
      sec: 2629800
    max:
      sessions:
        count: 5
  jwt:
    expiration:
      ms: 900000
  confirmation:
    expiration:
      days: 1

email:
  from:
    value: ${EMAIL_FROM_VALUE}

server:
  port: ${PORT:8080}
  error:
    path: /error
    include-message: never
    include-binding-errors: never
    whitelabel:
      enabled: false

spring:
  datasource:
#    url: ${DATABASE_URL}
    url: jdbc:postgresql://ep-divine-mouse-alb0as1v-pooler.c-3.eu-central-1.aws.neon.tech:5432/${DATABASE_NAME}?sslmode=require
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 15MB

  mvc:
    async:
      request-timeout: 30000

  mail:
    host: ${SMTP_MAIL_HOST}
    port: ${SMTP_MAIL_PORT}
    username: ${SMTP_LOGIN}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.springframework.core.events.SpringDocAppInitializer: ERROR
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
