app:
  url:
    frontend: ${FRONTEND_URL}
    backend: ${BACKEND_URL}
  limits:
    max-wishlists: 100
    max-items-per-list: 50

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  refresh:
    expiration:
      sec: 600
    max:
      sessions:
        count: 5
  jwt:
    expiration:
      ms: 6000000
  confirmation:
    expiration:
      days: 1

email:
  from:
    value: ${EMAIL_FROM_VALUE}

server:
  port: ${PORT:8080}
  error:
    path: /error
    include-message: never
    include-binding-errors: never
    whitelabel:
      enabled: false

spring:
  datasource:
#    url: ${DATABASE_URL}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
        format_sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 15MB

  mvc:
    async:
      request-timeout: 30000

  mail:
    host: ${SMTP_MAIL_HOST}
    port: ${SMTP_MAIL_PORT}
    username: ${SMTP_LOGIN}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
