app.url.frontend=${FRONTEND_URL}
app.url.backend=${BACKEND_URL}
app.limits.max-wishlists=100
app.limits.max-items-per-list=50

token.signing.key = ${TOKEN_SIGNING_KEY}
token.refresh.expiration.sec=600
token.refresh.max.sessions.count=5
token.jwt.expiration.ms=6000000
token.confirmation.expiration.days=1

spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
spring.datasource.username=${DATABASE_LOGIN}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quuted_identifiers=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10000MB
spring.servlet.multipart.max-request-size=10000MB

spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.async.request-timeout=3600000

server.port=8080
server.error.path=/error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.whitelabel.enabled=false

spring.mail.host=${SMTP_MAIL_HOST}
spring.mail.port=${SMTP_MAIL_PORT}
spring.mail.username=${SMTP_LOGIN}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
email.from.value=${EMAIL_FROM_VALUE}
