package com.api.wishoria.service.ai.util;

import lombok.extern.slf4j.Slf4j;
import org.springframework.util.StringUtils;

import java.math.BigDecimal;
import java.net.URI;

/**
 * Utility class for parsing, sanitizing, and validating unpredictable data
 * generated by AI models.
 */
@Slf4j
public final class AiResponseSanitizationUtil {

    private AiResponseSanitizationUtil() {
    }

    /**
     * Truncates a string to a specified maximum length.
     * If the string is shorter than the maximum length, it is returned as is.
     *
     * @param value     the original string
     * @param maxLength the maximum allowed length
     * @return the truncated string, or null if the input was null
     */
    public static String truncate(String value, int maxLength) {
        if (value == null) {
            return null;
        }
        return value.length() > maxLength ? value.substring(0, maxLength) : value;
    }

    /**
     * Safely parses a string into a BigDecimal, stripping out any non-numeric
     * characters (like currency symbols, spaces, or letters).
     *
     * @param priceStr the raw price string generated by AI (e.g., "$500.00", "~50")
     * @return the parsed BigDecimal, or null if parsing fails or input is blank
     */
    public static BigDecimal parsePriceSafe(String priceStr) {
        if (!StringUtils.hasText(priceStr)) {
            return null;
        }

        try {
            String cleanPrice = priceStr.replaceAll("[^\\d.]", "");
            return new BigDecimal(cleanPrice);
        } catch (NumberFormatException ex) {
            log.warn("Failed to parse AI generated price: {}", priceStr);
            return null;
        }
    }

    /**
     * Validates and sanitizes a URL string.
     * Ensures the URL is properly formatted and uses HTTP/HTTPS protocols.
     *
     * @param urlStr the raw URL string generated by AI
     * @return the valid URL string, or null if invalid or blank
     */
    public static String sanitizeUrl(String urlStr) {
        if (!StringUtils.hasText(urlStr)) {
            return null;
        }

        try {
            URI uri = URI.create(urlStr);
            if ("http".equalsIgnoreCase(uri.getScheme()) || "https".equalsIgnoreCase(uri.getScheme())) {
                return urlStr;
            }
        } catch (IllegalArgumentException e) {
            log.warn("AI hallucinated an invalid URL: {}", urlStr);
        }
        return null;
    }

}
